runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: gaesportsdata/static/images/favicon.ico
  upload: gaesportsdata/static/images/favicon\.ico
- url: /static
  static_dir: gaesportsdata/static
- url: /scrape.*
  script: gaesportsdata.app
  login: admin
- url: /.*
  script: gaesportsdata.app
  
libraries:
- name: jinja2
  version: latest
- name: lxml
  version: latest